export const APP_ACTIONS = {
  RESET_JOBS: 'RESET_JOBS',
  SET_JOBS: 'SET_JOBS',
  SET_JOB: 'SET_JOB',
  SET_CATEGORY: 'SET_CATEGORY',
  UPDATE_JOB_FAVORITES: 'UPDATE_JOB_FAVORITES'
}

export default { APP_ACTIONS }
